"""PreToolUse hook guard — dynamic script generation from credential guard sets."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from harnessbox.security.policy import SecurityPolicy


def build_guard_script(policy: SecurityPolicy) -> str:
    """Generate the PreToolUse hook script from a SecurityPolicy.

    The script's BLOCKED list is populated from the merged guard set's
    hook_regexes, ensuring the hook and settings.json derive from the
    same source of truth.
    """
    from harnessbox.security.guards import ALL_GUARD_NAMES, merge_guard_sets
    from harnessbox.security.policy import resolve_credential_guards

    guard_names = resolve_credential_guards(policy)
    if guard_names is None:
        guard_names = ALL_GUARD_NAMES

    merged = merge_guard_sets(guard_names)

    blocked_lines = []
    for regex in merged.hook_regexes:
        escaped = regex.replace("\\", "\\\\").replace('"', '\\"')
        blocked_lines.append(f'    r"{escaped}",')

    blocked_list = "\n".join(blocked_lines)

    return (
        "#!/usr/bin/env python3\n"
        '"""PreToolUse hook guard — blocks bash commands that access credentials.\n'
        "\n"
        "Generated by HarnessBox. Do not edit manually.\n"
        "\n"
        "Exit codes:\n"
        "  0 = allow (also used on errors — fail-open)\n"
        "  2 = block\n"
        '"""\n'
        "import json\n"
        "import re\n"
        "import sys\n"
        "\n"
        "BLOCKED = [\n"
        f"{blocked_list}\n"
        "]\n"
        "\n"
        "_COMPILED = [re.compile(p) for p in BLOCKED]\n"
        "\n"
        "\n"
        "def main() -> None:\n"
        "    try:\n"
        "        event = json.loads(sys.stdin.read())\n"
        "    except Exception:\n"
        "        sys.exit(0)\n"
        "\n"
        '    tool_name = event.get("tool_name", "")\n'
        '    if tool_name != "Bash":\n'
        "        sys.exit(0)\n"
        "\n"
        '    tool_input = event.get("tool_input", {})\n'
        '    command = tool_input.get("command", "")\n'
        "\n"
        "    for pattern in _COMPILED:\n"
        "        if pattern.search(command):\n"
        "            result = {\n"
        '                "hookSpecificOutput": {"permissionDecision": "deny"},\n'
        '                "systemMessage": (\n'
        '                    f"Blocked: command matches credential-access pattern'
        ' {pattern.pattern!r}"\n'
        "                ),\n"
        "            }\n"
        "            print(json.dumps(result))\n"
        "            sys.exit(2)\n"
        "\n"
        "    sys.exit(0)\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )
