"""Cost tracking types and utilities for AI coding agent sessions.

Tracks per-session cost metrics with per-model breakdown. Cost data is accumulated
from the agent's `/cost` command output during persistent sessions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class ModelCost:
    """Cost metrics for a single model used in a session.

    Attributes:
        input_tokens: Number of input tokens sent to this model.
        output_tokens: Number of output tokens generated by this model.
        cost_usd: Total cost in USD for this model's usage.
    """

    input_tokens: int
    output_tokens: int
    cost_usd: float


@dataclass(frozen=True)
class CostMetrics:
    """Aggregated cost metrics for a sandbox session.

    Costs accumulate across multiple prompts/turns. The dataclass is frozen
    (immutable) so `sandbox.cost_metrics` returns a snapshot, not a live reference.

    Attributes:
        total_cost_usd: Total cost across all models and turns.
        per_model: Cost breakdown by model name (e.g., "claude-sonnet-4.5").
            Keys are fully-qualified model names from the API response.
        turn_count: Number of turns (prompts) that contributed to these costs.
        last_updated: ISO 8601 timestamp of the last cost update.

    Example::

        metrics = sandbox.cost_metrics
        print(f"Total: ${metrics.total_cost_usd:.4f}")
        for model, cost in metrics.per_model.items():
            print(f"  {model}: ${cost.cost_usd:.4f} ({cost.input_tokens} in, {cost.output_tokens} out)")
    """

    total_cost_usd: float = 0.0
    per_model: dict[str, ModelCost] = field(default_factory=dict)
    turn_count: int = 0
    last_updated: str | None = None


def parse_cost_data(cost_data: dict[str, Any]) -> CostMetrics | None:
    """Parse cost data from the `/cost` command output.

    Extracts `total_cost_usd` and `modelUsage` from the response. If `modelUsage`
    is missing or malformed, falls back to parsing text output.

    Args:
        cost_data: Raw response from `agent_process.send_command("/cost")`.
            Expected fields: `total_cost_usd` (float), `modelUsage` (dict), or `output` (str).

    Returns:
        CostMetrics with parsed data, or None if cost_data is empty or invalid.

    Example cost_data structure::

        {
            "total_cost_usd": 0.012,
            "modelUsage": {
                "claude-haiku-4.5": {
                    "inputTokens": 123,
                    "outputTokens": 52,
                    "costUSD": 0.0004
                },
                "claude-sonnet-4.5": {
                    "inputTokens": 3,
                    "output_tokens": 68,
                    "costUSD": 0.0116
                }
            }
        }
    """
    import re
    from datetime import datetime, timezone

    if not cost_data:
        return None

    total_cost = cost_data.get("total_cost_usd")
    per_model: dict[str, ModelCost] = {}

    # Try structured modelUsage first
    model_usage = cost_data.get("modelUsage", {})
    if isinstance(model_usage, dict):
        for model_name, usage in model_usage.items():
            if not isinstance(usage, dict):
                continue

            # Handle both camelCase (API) and snake_case field names
            input_tokens = usage.get("inputTokens", usage.get("input_tokens", 0))
            output_tokens = usage.get("outputTokens", usage.get("output_tokens", 0))
            cost_usd_raw = usage.get("costUSD", usage.get("cost_usd"))

            # Skip models with missing cost data
            if cost_usd_raw is None:
                continue

            try:
                cost_usd = float(cost_usd_raw)
                per_model[model_name] = ModelCost(
                    input_tokens=int(input_tokens or 0),
                    output_tokens=int(output_tokens or 0),
                    cost_usd=cost_usd,
                )
            except (ValueError, TypeError):
                # Skip models with unparseable data
                continue

    # Fallback: parse text output if modelUsage not present
    if not per_model and "output" in cost_data:
        text = cost_data["output"]
        if isinstance(text, str):
            # Parse total cost from text if not already set
            if total_cost is None:
                total_match = re.search(r"Total cost:\s+\$?([\d.]+)", text)
                if total_match:
                    try:
                        total_cost = float(total_match.group(1))
                    except ValueError:
                        pass

            # Parse per-model usage lines
            # Format: "   model-name:  123 input, 456 output, ... ($1.23)"
            model_pattern = r"^\s+([a-z0-9_-]+):\s+(\d+)\s+input,\s+(\d+)\s+output.*?\(\$?([\d.]+)\)"
            for line in text.split("\n"):
                match = re.match(model_pattern, line, re.IGNORECASE)
                if match:
                    model_name = match.group(1)
                    input_tokens = int(match.group(2))
                    output_tokens = int(match.group(3))
                    cost_usd = float(match.group(4))
                    per_model[model_name] = ModelCost(
                        input_tokens=input_tokens,
                        output_tokens=output_tokens,
                        cost_usd=cost_usd,
                    )

    if total_cost is None:
        return None

    return CostMetrics(
        total_cost_usd=float(total_cost),
        per_model=per_model,
        turn_count=1,  # This represents one turn's cost
        last_updated=datetime.now(timezone.utc).isoformat(),
    )


def accumulate_costs(current: CostMetrics, new: CostMetrics) -> CostMetrics:
    """Accumulate new cost data into existing metrics.

    Merges per-model costs and updates totals. Used to aggregate costs across
    multiple turns in a session.

    Args:
        current: Existing cost metrics.
        new: New cost metrics from the latest turn.

    Returns:
        New CostMetrics with accumulated data (frozen dataclass).
    """
    # Merge per-model costs
    merged_per_model = dict(current.per_model)

    for model_name, new_cost in new.per_model.items():
        if model_name in merged_per_model:
            existing = merged_per_model[model_name]
            merged_per_model[model_name] = ModelCost(
                input_tokens=existing.input_tokens + new_cost.input_tokens,
                output_tokens=existing.output_tokens + new_cost.output_tokens,
                cost_usd=existing.cost_usd + new_cost.cost_usd,
            )
        else:
            merged_per_model[model_name] = new_cost

    return CostMetrics(
        total_cost_usd=current.total_cost_usd + new.total_cost_usd,
        per_model=merged_per_model,
        turn_count=current.turn_count + new.turn_count,
        last_updated=new.last_updated,
    )
