"""Workspace name generator using memorable city names from history and fiction."""

import random

_NAMES: tuple[str, ...] = (
    # Ancient cities
    "Alexandria",
    "Babylon",
    "Carthage",
    "Constantinople",
    "Persepolis",
    "Thebes",
    "Troy",
    "Petra",
    "Memphis",
    "Angkor",
    "Tenochtitlan",
    "Machu Picchu",
    "Palmyra",
    "Ephesus",
    "Timbuktu",
    "Samarkand",
    "Leptis Magna",
    "Mohenjo Daro",
    "Harappa",
    "Taxila",
    "Athens",
    "Sparta",
    "Rome",
    "Pompeii",
    "Delphi",
    "Mycenae",
    "Nineveh",
    "Ur",
    "Eridu",
    "Uruk",
    "Jericho",
    "Damascus",
    "Aleppo",
    "Baghdad",
    "Isfahan",
    "Shiraz",
    "Kyoto",
    "Nara",
    "Edo",
    "Beijing",
    "Xi'an",
    "Luoyang",
    "Kaifeng",
    "Hangzhou",
    "Angkor Wat",
    "Ayutthaya",
    "Sukhothai",
    "Pagan",
    "Borobudur",
    "Prambanan",
    "Hampi",
    "Vijayanagara",
    "Pataliputra",
    "Nalanda",
    "Varanasi",
    "Ujjain",
    "Taxila",
    "Knossos",
    "Akrotiri",
    "Phaistos",
    "Gortyn",
    "Olympia",
    "Corinth",
    "Argos",
    "Miletus",
    "Pergamon",
    "Sardis",
    "Tyre",
    "Sidon",
    "Byblos",
    "Carthago Nova",
    "Tarraco",
    "Emerita Augusta",
    "Londinium",
    "Eboracum",
    "Aquincum",
    "Vindobona",
    "Carnuntum",
    "Colonia Agrippina",
    "Augusta Treverorum",
    "Mediolanum",
    "Ravenna",
    "Syracuse",
    "Tarentum",
    "Capua",
    "Cumae",
    "Paestum",
    "Herculaneum",
    "Volubilis",
    "Timgad",
    "Djemila",
    "Hippo Regius",
    "Cirta",
    "Thugga",
    "Dougga",
    "Sufetula",
    "Sbeitla",
    # Kingdoms and mythical places
    "Avalon",
    "Camelot",
    "Gondolin",
    "Numenor",
    "Valinor",
    "Asgard",
    "Olympus",
    "Elysium",
    "Valhalla",
    "Shangri-La",
    "El Dorado",
    "Atlantis",
    "Lemuria",
    "Shambhala",
    "Xanadu",
    "Hyperborea",
    "Arcadia",
    # Sci-fi and fictional cities
    "Arrakis",
    "Coruscant",
    "Trantor",
    "Solaris",
    "Pandora",
    "Cybertron",
    "Krypton",
    "Wakanda",
    "Gotham",
    "Midgar",
    "Hyrule",
    "Rapture",
    "Columbia",
    "Terminus",
    "Ankh-Morpork",
    "Rivendell",
    "Lothlorien",
    "Minas Tirith",
    "Isengard",
    "Edoras",
    "Erebor",
    "Dale",
    "Esgaroth",
    "Bree",
    "Hobbiton",
    "Michel Delving",
    "Osgiliath",
    "Minas Morgul",
    "Barad-dur",
    "Dol Guldur",
    "Weathertop",
    "Fornost",
    "Annuminas",
    "Tharbad",
    "Pelargir",
    "Umbar",
    "Harad",
    "Rhun",
    "Khand",
    "Dorwinion",
    # Space and planets
    "Kepler",
    "Proxima",
    "Andromeda",
    "Cygnus",
    "Orion",
    "Centauri",
    "Nebula",
    "Pulsar",
    "Quasar",
    "Nova",
    "Supernova",
    "Stellar",
    "Celestia",
    "Aurora",
    "Eclipse",
    "Equinox",
    "Solstice",
    "Zenith",
    "Nadir",
    "Meridian",
    "Horizon",
    "Cosmos",
    "Galaxy",
    "Astral",
    "Lunar",
    "Solar",
    "Sirius",
    "Vega",
    "Altair",
    "Deneb",
    "Rigel",
    "Betelgeuse",
    "Antares",
    "Aldebaran",
    "Spica",
    "Arcturus",
)

_used: set[str] = set()


def generate_workspace_name() -> str:
    """
    Return a unique city name from the pool.

    Names are lowercase and hyphenated for use as git branch/directory names.
    When the pool is exhausted, it resets and starts over.

    Returns:
        A unique workspace name (e.g., "machu-picchu", "coruscant")
    """
    available = [n for n in _NAMES if n not in _used]
    if not available:
        _used.clear()
        available = list(_NAMES)
    name = random.choice(available)
    _used.add(name)
    return name.lower().replace(" ", "-")
